@extends('layout.app')
@section('appcontents')
    <h1 class="p-2 m-2">Home</h1>
    <p class="p-2 m-2">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos vitae, modi sint architecto at eaque totam harum, cumque eos eius unde velit natus debitis praesentium magni corporis fugiat neque officia facere explicabo excepturi! Doloremque minus illo placeat sed libero sint earum distinctio cumque, commodi ex aspernatur magnam sequi maiores, dolore id corrupti laboriosam fuga accusamus fugit excepturi ipsa nihil itaque. Repudiandae quos omnis veniam blanditiis. Blanditiis minima sed voluptates, unde corporis laudantium aut illo illum dolores pariatur quas accusamus dignissimos at sapiente quae atque? Sint, tempore. Officiis dicta eius laborum rerum minus, facere magni dolorum cum tempore inventore illum quidem?</p>
    <p class="p-2 m-2">Quibusdam suscipit unde quo dignissimos cum autem quam optio inventore atque aliquid illum repellat, fuga minus nostrum reprehenderit minima accusamus quaerat! Alias veniam asperiores ea facilis vel tempora accusamus repellendus commodi, vero fuga magnam, corrupti omnis possimus quibusdam! Commodi, sapiente! Non voluptate doloribus a ipsam veniam cum, tenetur omnis quae hic voluptatum animi illum id laudantium fugit deserunt cupiditate ut. Assumenda quisquam eaque voluptate ad sapiente accusamus error quod, quasi suscipit culpa omnis blanditiis provident repellat. Minus quas illo, expedita aliquid ad culpa quis amet numquam quisquam sapiente sunt error dolore magni cupiditate saepe quaerat dicta deleniti nihil. Omnis, amet!</p>
    <p class="p-2 m-2">Aspernatur magnam iure ipsa illo? Et nisi unde laudantium vel doloribus. Esse explicabo nulla ad maxime, consequatur nihil ab aperiam neque soluta exercitationem? Odio repellat aut voluptas natus voluptatum. Ipsam eius voluptates aliquam quisquam mollitia error possimus rerum, totam itaque, tenetur ex maiores iste at nisi pariatur aliquid omnis enim velit a blanditiis tempora doloremque. Commodi voluptates repellendus totam. Alias aliquam, est debitis velit, possimus doloremque labore sequi nesciunt incidunt neque unde consectetur et accusamus quae. Nisi natus dolorem animi quibusdam optio, doloremque recusandae, nulla esse rerum itaque, nemo consequuntur assumenda hic autem nostrum? Quibusdam autem voluptatem ratione commodi praesentium.</p>
    <p class="p-2 m-2">Ipsum nihil, quae magni saepe repellat cumque facilis doloremque ullam consequatur voluptate quo consequuntur porro! Delectus obcaecati quod corporis commodi vitae. Incidunt aut pariatur veniam alias officia quis, eius deserunt laboriosam dignissimos facere, laudantium, veritatis vero deleniti asperiores nam esse dolores explicabo voluptatibus! Voluptate, doloremque distinctio sequi vel impedit nam sint sunt aspernatur blanditiis aut deleniti, minus laboriosam eligendi. Iure, alias quaerat hic dolore, in ratione, obcaecati quasi impedit maiores reiciendis voluptates totam aperiam consequatur minus porro expedita assumenda ipsa vel dicta facere ullam harum temporibus? Quod, harum ipsam amet enim optio quam eaque, recusandae placeat illum aperiam numquam autem.</p>
    <p class="p-2 m-2">Excepturi, ad alias quisquam sunt deserunt aspernatur voluptates nemo fugiat nobis ipsa praesentium adipisci odio hic quibusdam molestiae provident voluptatibus omnis aliquid error minima! Non modi eaque saepe deleniti reiciendis! Nisi temporibus, quam aut cupiditate fuga in quia dolor eaque minima, delectus, nobis nemo et odio explicabo veniam dignissimos quis dolores! Vel est sunt sapiente qui temporibus quae labore molestiae itaque, natus inventore ut, blanditiis eligendi, possimus animi necessitatibus deserunt dolore? Reiciendis itaque impedit culpa, mollitia excepturi vel voluptas sequi similique odit ducimus corrupti quos tempore dicta repudiandae quidem repellat aut, quia beatae voluptatum! Mollitia animi optio provident vero sed!</p>
@endsection
